baseURL: "https://panosni.github.io" 
title: Panayiotis Nicolaides
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: papers/
          weight: 1
        - name: Talks
          url: talks/
          weight: 2
        - name: Resume
          url: nicolaides_cv.pdf
          weight: 3 

params:
    description: "I am Director of Research at the EU Tax Observatory, Paris School of Economics. I specialise in public economics and taxation, in particular tax compliance and the empirical analysis of tax policy using administrative data.
The majority of my work is guided closely by policy developments, having spent the first part of my career (2013-2019) managing the Greek economic crisis in Brussels and Athens. Since 2021, I have been working on establishing the EU Tax Observatory in Paris; I direct its scientific programme, coordinate research output and manage relations with external stakeholders."
    author: Panayiotis Nicolaides
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","talks","resume"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Panayiotis Nicolaides
          subtitle: "I am Director of Research at the EU Tax Observatory, Paris School of Economics. Previously I served at Special Economic Advisor to finance ministers in Greece during the Greek economic crisis. I was the Alternate Member at the Eurogroup Working Group and Alternate Director at the European Stability Mechanism. I worked also for the European Commission at the beginning of my career."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Panayiotis Nicolaides
          buttons:
            - name: Publications
              url: papers/
            - name: Talks
              url: talks/
            - name: Resume
              url: nicolaides_cv.pdf

    socialIcons:
     #   - name: cv
    #    url: cv.pdf
        - name: Email
          url: mailto:pan.nicolaides@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ZNxFqicAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/panosni
        - name: Twitter
          url: https://twitter.com/pnicolaides
        - name: LinkedIn
          url: https://linkedin.com/in/panayiotis-nicolaides-07342242

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Panayiotis Nicolaides"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2